name: Steven Bailey Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91653
title: Steven Bailey Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cacaca'
    - '#ababab'
    - '#8c8c8c'
    - '#4c4c4c'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
