name: Steven Bailey Photography
favicon: null
layout_spectrum: 0.17196969082579017
typography_spectrum: 0.5520500496495515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6161101404577494
  lightness: 0.22462422330863774
  saturation: 0.4589036591351032
  rhythmicContrast: 0.411165168043226
purpose: []
