name: Steven Bailey Photography
favicon: null
layout_spectrum: 0.95578
typography_spectrum: 0.80112
title: Steven Bailey Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#595959'
    - '#7d7d7d'
    - '#c5c5c5'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.411165168043226
purpose: []
